version: "3.9"

services:
  app:
    image: mcr.microsoft.com/devcontainers/javascript-node:1-18-bullseye
    container_name: web_push_codelab_app
    tty: true
    working_dir: /opt/app
    volumes:
      - ..:/opt/app:delegated

  nginx:
    image: nginx:latest
    container_name: web_push_codelab_nginx
    volumes:
      - ../app:/usr/share/nginx/html:delegated
    ports:
      - 8000:80
